export {default as basket} from './audio/01 basket.mp3';
export {default as asake} from './audio/asake-dull.mp3';
export {default as homeless} from './audio/01 Black Sherif - The Homeless Song (NetNaija.com).mp3';
export {default as pourMeWater} from './audio/01 Kizz Daniel - Pour Me Water (NetNaija.com).mp3';
export {default as anotherLevel} from './audio/01 Olamide - Another Level (NetNaija.com).mp3';
export {default as noTime} from './audio/01 Olamide - No Time (NetNaija.com).mp3';
export {default as oilInMyHead} from './audio/02 Black Sherif - Oil in my Head (NetNaija.com).mp3';
export {default as addict} from './audio/02 Kizz Daniel - Addict (NetNaija.com).mp3';
export {default as greenLight} from './audio/02 Olamide - Green Light (NetNaija.com).mp3';
export {default as jailer} from './audio/02 Olamide - Jailer (feat. Jaywillz) (NetNaija.com).mp3';
export {default as warlords} from './audio/02 Olamide - Warlords (feat. Snow, Phyno, Cheque & Rhatti) (NetNaija.com).mp3';
export {default as organise} from './audio/03 Asake - Organise (NetNaija.com).mp3';
export {default as a45} from './audio/03 Black Sherif - 45 (NetNaija.com).mp3';
export {default as ehGod} from './audio/03 Kizz Daniel - Eh God (Barnabas) (NetNaija.com).mp3';
export {default as billionTalk} from './audio/03 Olamide - Billion Talk (feat. Milly) (NetNaija.com).mp3';
export {default as infinity} from './audio/03 Olamide - Infinity (feat. Omah Lay) (NetNaija.com).mp3';
export {default as blessingFollowMe} from './audio/04 Chidinma - Blessings Follow Me (feat. KS Bloom) (NetNaija.com).mp3';
export {default as oshe} from './audio/04 Kizz Daniel - Oshe (feat. The Cavemen.) (NetNaija.com).mp3';
export {default as danceWithTheDevil} from './audio/04 Olamide - Dance With the Devil (feat. Sosa-E & Jackmillz) (NetNaija.com).mp3';
export {default as julie} from './audio/04 Olamide - Julie (NetNaija.com).mp3';
export {default as dupe} from './audio/05 Asake - Dupe (NetNaija.com).mp3';
export {default as preyDaYoungsta} from './audio/05 Black Sherif - Prey Da Youngsta (NetNaija.com).mp3';
export {default as burn} from './audio/05 Kizz Daniel - Burn (NetNaija.com).mp3';
export {default as roughUp} from './audio/05 Olamide - Rough Up (feat. Layydoe) (NetNaija.com).mp3';
export {default as triumphant} from './audio/05 Olamide - Triumphant (feat. Bella Shmurda) (NetNaija.com).mp3';
export {default as wonma} from './audio/05 Olamide - Wonma (NetNaija.com).mp3';
export {default as muse} from './audio/06 Asake - Muse (NetNaija.com).mp3';
export {default as sadBoysDontFold} from "./audio/06 Black Sherif - Sad Boys Don't Fold (NetNaija.com).mp3";
export {default as atYourService} from './audio/06 Olamide - At Your Service (NetNaija.com).mp3';
export {default as want} from './audio/06 Olamide - Want (feat. Fave) (NetNaija.com).mp3';
export {default as demons} from './audio/06 Olamide - Demons (feat. Jackmillz) (NetNaija.com).mp3';
export {default as joha} from './audio/07 Asake - Joha (NetNaija.com).mp3';
export {default as konongoZongo} from './audio/07 Black Sherif - Konongo Zongo (NetNaija.com).mp3';
export {default as skin} from './audio/07 Kizz Daniel & Kelvyn Colt - Skin (NetNaija.com).mp3';
export {default as doBetter} from './audio/07 Olamide - Do Better (NetNaija.com).mp3';
export {default as mojo} from './audio/07 Olamide - Mojo (feat. JayBoi) (NetNaija.com).mp3';
export {default as ponpon} from './audio/07 Olamide - PonPon (feat. Fave) (NetNaija.com).mp3';
export {default as nzaza} from './audio/08 Asake - Nzaza (NetNaija.com).mp3';
export {default as Wasteman} from './audio/08 Black Sherif - Wasteman (NetNaija.com) (1).mp3';
export {default as Chimichanga} from './audio/08 Olamide - Chimichanga (NetNaija.com).mp3';
export {default as Prophesy} from './audio/08 Olamide - Prophesy (NetNaija.com).mp3';
export {default as Ototo} from './audio/09 Asake - Ototo (NetNaija.com).mp3';
export {default as weUp} from './audio/09 Black Sherif - We Up (NetNaija.com).mp3';
export {default as richAndFamous} from './audio/09 Olamide - Rich & Famous (NetNaija.com).mp3';
export {default as Shilalo} from './audio/09 Olamide - Shilalo (feat. Phyno) (NetNaija.com).mp3';
export {default as Somebody} from './audio/09 Olamide - Somebody (feat. Phyno) (NetNaija.com).mp3';
export {default as reason} from './audio/10 Asake - Reason (feat. Russ) (NetNaija.com).mp3';
export {default as toxicLove} from './audio/10 Black Sherif - Toxic Love City (NetNaija.com).mp3';
export {default as loading} from './audio/10 Olamide - Loading (feat Bad Boy Timz) (NetNaija.com) (1).mp3';
export {default as soMuchLove} from './audio/10 Olamide - So Much More (NetNaija.com).mp3';
export {default as Sunmomi} from './audio/11 Asake - Sunmomi (NetNaija.com).mp3';
export {default as dontForgetMe} from "./audio/11 Black Sherif - Don't Forget Me (NetNaija.com).mp3";
export {default as Unconditionally} from './audio/11 Olamide - Unconditionally (feat. Peruzzi) (NetNaija.com).mp3';
export {default as ohParadise} from './audio/12 Black Sherif - Oh Paradise (NetNaija.com).mp3';
export {default as plenty} from './audio/12 Olamide - Plenty (feat. Fireboy DML) (NetNaija.com).mp3';
export {default as rush} from './audio/13 Ayra Starr - Rush (NetNaija.com).mp3';
export {default as Traveler} from './audio/13 Black Sherif - Kweku The Traveler (NetNaija.com).mp3';
export {default as secondSermon} from './audio/14 Black Sherif & Burna Boy - Second Sermon (Remix) (NetNaija.com).mp3';
export {default as PBUH} from './audio/Asake - Peace Be Unto You (PBUY) (NetNaija.com).mp3';
export {default as sungba} from './audio/Asake - Sungba (Remix) [feat. Burna Boy] (NetNaija.com).mp3';
export {default as terminator} from './audio/Asake - Terminator (NetNaija.com).mp3';
export {default as soja} from './audio/Black Sherif - Soja (NetNaija.com) (1).mp3';
export {default as backInUni} from './audio/Blaqbonez & JAE5 - Back in Uni (NetNaija.com).mp3';
export {default as forYou} from './audio/Chidinma - For You (feat. Fiokee) (NetNaija.com).mp3';
export {default as watchingAllOverMe} from './audio/Chiké & Ada Ehi - Watching All Over Me (NetNaija.com).mp3';
export {default as kos} from './audio/Chinyere Udoma - Eze Mmuo (King of the Spirits) (NetNaija.com).mp3';
export {default as ngidp} from './audio/Chioma Jesus - Na God I Dey Praise (Craze) (NetNaija.com).mp3';
export {default as shoutForJoy} from './audio/Chissom Anthony - Shout for Joy.mp3';
export {default as AfrohitMix} from './audio/DJ Baddo - Afrohit Mix (Vol. 4) (NetNaija.com).mp3';
export {default as Howareyou} from './audio/Johnny Drille - How Are You (My Friend) (NetNaija.com).mp3';
export {default as yourGrace} from './audio/Judikay - Your Grace (NetNaija.com).mp3';
export {default as cough} from './audio/Kizz Daniel - Cough (Odo) (NetNaija.com).mp3';
export {default as lie} from './audio/Kizz Daniel - Lie (NetNaija.com).mp3';
export {default as praiseLoveSong} from './audio/Mr M & Revelation - Praise Love Songs (NetNaija.com).mp3';
export {default as freedomPraise} from './audio/Mr. M & Revelation - FREEDOM PRAISE (NetNaija.com).mp3';
export {default as neverFail} from './audio/Nikki Laoye - Never Fail (NetNaija.com).mp3';
export {default as chokoMilo} from './audio/Olamide - Choko Milo (NetNaija.com).mp3';
export {default as eru} from './audio/Olamide - Eru (NetNaija.com).mp3';
export {default as pawon} from './audio/Olamide - Pawon (NetNaija.com).mp3';
export {default as rock} from './audio/Olamide - Rock (NetNaija.com).mp3';
export {default as weOutside} from './audio/Olamide - We Outside (NetNaija.com).mp3';
export {default as calmDown} from './audio/Rema & Selena Gomez - Calm Down (NetNaija.com).mp3';
export {default as COD} from './audio/Zinoleesky - Call of Duty (NetNaija.com).mp3';